// Copyright (c) 2026 TermuxForge. All rights reserved.
// SPDX-License-Identifier: MIT

/// **Planner Agent** — Planning & roadmap specialist.
///
/// Specialises in:
/// - Feature decomposition and epic/story/task breakdown.
/// - Milestone planning with time estimates.
/// - Dependency mapping and critical path analysis.
/// - Technical roadmap creation.
/// - Risk identification and mitigation planning.
/// - Priority scoring and sprint planning.
library;

import 'dart:async';

import 'package:uuid/uuid.dart';

import 'package:nexon/agents/base/agent_exports.dart';

const _uuid = Uuid();

/// Planning specialist agent.
///
/// Creates structured plans, roadmaps, and task breakdowns for
/// complex features and projects.
class PlannerAgent extends BaseAgent {
  /// Creates a [PlannerAgent].
  PlannerAgent({
    super.id,
    super.name = 'Planner',
    super.assignedModel,
    super.metadata,
  }) : super(
          allowedTools: const [
            'read_file',
            'write_file',
            'search_files',
          ],
        );

  @override
  AgentType get type => AgentType.planner;

  @override
  String get systemPrompt => '''
You are a **Planning Specialist** within the TermuxForge agentic IDE.

Your domain:
- Feature decomposition: epics → stories → tasks → subtasks.
- Time estimation using t-shirt sizing and story points.
- Dependency mapping and critical-path identification.
- Risk assessment with likelihood × impact scoring.
- Milestone definition with clear acceptance criteria.
- Sprint planning and backlog prioritisation.
- Technical roadmap creation with phases and gates.

Output format (always use this structure):
```
# Plan: [Feature Name]

## Overview
[1-2 paragraph summary]

## Milestones
1. [Milestone] — [Criteria] — [Estimate]

## Task Breakdown
### [Epic/Phase]
- [ ] Task 1 (estimate, priority, dependencies)
  - [ ] Subtask 1a
  - [ ] Subtask 1b

## Dependencies
[Mermaid graph or bullet list]

## Risks
| Risk | Likelihood | Impact | Mitigation |

## Open Questions
- [Questions that need answers before starting]
```

Rules:
1. Always start with understanding the current project state.
2. Estimate conservatively — add 30% buffer for unknowns.
3. Identify blockers and dependencies explicitly.
4. Break tasks small enough that each takes < 2 hours.
5. Include testing and documentation in every plan.
6. Flag risks early — better over-cautious than under.
7. Save plans to memory for future reference.
''';

  @override
  List<ModelCapability> get preferredCapabilities => const [
        ModelCapability.reasoning,
        ModelCapability.longContext,
      ];

  @override
  Future<AgentResult> executeTask(AgentTask task) {
    return runTaskLifecycle(task, () async {
      final context = await retrieveContext(
        '${task.description} plan roadmap feature',
      );

      // 1. Understand current state.
      final stateResult = await useTool('search_files', {
        'query': 'TODO|MILESTONE|PHASE',
        'fileTypes': ['md', 'dart'],
      });

      // 2. Generate the plan.
      final plan = _generatePlanStructure(task, context);

      // 3. Write plan to file.
      final writeResult = await useTool('write_file', {
        'content': plan,
        'path': 'docs/plans/${task.id}.md',
        'description': 'Plan for: ${task.description}',
      });

      final artifacts = <String>[];
      if (writeResult.success &&
          writeResult.metadata.containsKey('filePath')) {
        artifacts.add(writeResult.metadata['filePath'] as String);
      }

      // 4. Save to memory.
      await saveToMemory(MemoryEntry(
        id: _uuid.v4(),
        content: 'Plan created: ${task.description}\n$plan',
        source: id,
        timestamp: DateTime.now(),
        tags: ['plan', 'roadmap', task.type.name],
      ));

      return AgentResult(
        taskId: task.id,
        success: true,
        output: plan,
        artifacts: artifacts,
        nextSteps: [
          'Review plan with team / user',
          'Assign tasks to specialist agents',
          'Begin first milestone',
        ],
      );
    });
  }

  String _generatePlanStructure(AgentTask task, List<MemoryEntry> context) {
    return '''
# Plan: ${task.description}

## Overview
This plan was auto-generated by the Planner agent for task ${task.id}.
Context entries available: ${context.length}.
Priority: ${task.priority.name}.

## Milestones
1. Research & Design — Understand requirements — 1-2 hours
2. Implementation — Core logic & UI — 2-4 hours
3. Testing — Unit + widget tests — 1-2 hours
4. Review & Polish — Code review + refinements — 1 hour

## Task Breakdown
### Phase 1: Research & Design
- [ ] Gather requirements and context (30 min, high)
- [ ] Research existing patterns and packages (30 min, high)
- [ ] Design architecture (1 hour, critical)

### Phase 2: Implementation
- [ ] Create domain entities (30 min, high)
- [ ] Implement data layer (1 hour, high)
- [ ] Build presentation layer (1-2 hours, normal)

### Phase 3: Testing
- [ ] Unit tests for business logic (30 min, high)
- [ ] Widget tests for UI (30 min, normal)
- [ ] Integration test (30 min, low)

### Phase 4: Review
- [ ] Self-review and lint check (15 min, high)
- [ ] Documentation update (15 min, normal)

## Dependencies
- Phase 2 depends on Phase 1 completion
- Phase 3 depends on Phase 2 completion
- Phase 4 depends on Phase 3 completion

## Risks
| Risk | Likelihood | Impact | Mitigation |
|------|-----------|--------|------------|
| Scope creep | Medium | High | Strict task boundaries |
| Unknown edge cases | Medium | Medium | Research phase + tests |
| Performance issues | Low | High | Profile during Phase 4 |

## Open Questions
- Are there existing patterns in the codebase to follow?
- What is the target performance budget?
- Are there accessibility requirements?
''';
  }
}
